settings:
  number_of_replicas: 1
  number_of_shards: 1
  refresh_interval: 60s
mappings:
  dynamic: false
  properties:
    name:
      type: text
      analyzer: english
      fields:
        autocomplete:
          type: text
          analyzer: app_autocomplete
          search_analyzer: standard

      # type: text
      # analyzer: english
      # fields:
      #   keyword:
      #     type: keyword
